dist: trusty
sudo: false
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libfontconfig1
      - libgconf-2-4
      - libnss3
install: "npm install"
script: "./test-driver.sh"